#!/usr/bin/env python3
"""Build the Synopsys API tube-style map.

Generated by batch generator. 
"""

import sys
from pathlib import Path

sys.path.insert(0, "/Users/kinlane/GitHub/all/.claude/skills")
from _subway_engine import build_subway  # noqa: E402

ABBREV = {

}

LINES = [
    {
        "name": 'Synopsys AppSec',
        "color": '#00396B',
        "closed": True,
        "stations": [
        ('Polaris', (640, 260)),
        ('Coverity', (840, 460)),
        ('Cloud OpenLink', (640, 660)),
        ('Seeker', (440, 460)),
        ],
    },
]

URL_OVERRIDES = {
    'Polaris': 'https://apis.apis.io/apis/synopsys/polaris/',
    'Coverity': 'https://apis.apis.io/apis/synopsys/coverity/',
    'Cloud OpenLink': 'https://apis.apis.io/apis/synopsys/cloud-openlink/',
    'Seeker': 'https://apis.apis.io/apis/synopsys/seeker/',
}


def main():
    seen = set()
    n_unique = 0
    for ln in LINES:
        for (st, _) in ln["stations"]:
            if st not in seen:
                n_unique += 1
                seen.add(st)
    build_subway(
        title='The Synopsys API · Underground Map',
        subtitle=f"{n_unique} APIs · {len(LINES)} functional lines · click any station for the apis.io page",
        lines=LINES,
        abbrev=ABBREV,
        source_label='Source: synopsys/openapi · github.com/api-evangelist/synopsys',
        out_dir=Path(__file__).resolve().parent,
        out_basename='synopsys-subway-map',
        provider_id='synopsys',
        station_url_overrides=URL_OVERRIDES,
    )


if __name__ == "__main__":
    main()
